"""added passwrod hash for galleries

Revision ID: 0b3515be5a77
Revises: 8b825436b0ed
Create Date: 2025-09-29 14:48:06.522606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3515be5a77'
down_revision: Union[str, Sequence[str], None] = '8b825436b0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galleries', 'password_hash')
    # ### end Alembic commands ###
