"""Added reset_at

Revision ID: 0b79fc7de341
Revises: bb603aa43ae6
Create Date: 2025-10-16 13:27:19.495472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b79fc7de341'
down_revision: Union[str, Sequence[str], None] = 'bb603aa43ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('resets_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galleries', 'resets_at')
    # ### end Alembic commands ###
