"""removed previews

Revision ID: 57e34f896742
Revises: 843f7d68c278
Create Date: 2026-06-09 18:05:08.377014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e34f896742'
down_revision: Union[str, Sequence[str], None] = '843f7d68c278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'path_thumb')
    op.drop_column('photos', 'path_preview')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('path_preview', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('photos', sa.Column('path_thumb', sa.VARCHAR(length=1024), nullable=True))
    # ### end Alembic commands ###
