"""added favorites

Revision ID: 95bbfb1c9458
Revises: fd8eb52da5c5
Create Date: 2025-10-01 07:19:35.767618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bbfb1c9458'
down_revision: Union[str, Sequence[str], None] = 'fd8eb52da5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('selector', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gallery_id', 'photo_id', 'selector', name='uq_favorite_unique')
    )
    op.create_index(op.f('ix_favorites_gallery_id'), 'favorites', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_photo_id'), 'favorites', ['photo_id'], unique=False)
    op.create_index(op.f('ix_favorites_selector'), 'favorites', ['selector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_selector'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_photo_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_gallery_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
