"""brnad_settings.py

Revision ID: 9f67b9357702
Revises: 0b3515be5a77
Create Date: 2025-09-30 18:46:14.342487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f67b9357702'
down_revision: Union[str, Sequence[str], None] = '0b3515be5a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_name', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('wm_enabled', sa.Boolean(), nullable=True),
    sa.Column('wm_use_logo', sa.Boolean(), nullable=True),
    sa.Column('wm_text', sa.String(length=200), nullable=True),
    sa.Column('wm_opacity', sa.Float(), nullable=True),
    sa.Column('wm_position', sa.String(length=12), nullable=True),
    sa.Column('wm_scale', sa.Float(), nullable=True),
    sa.Column('wm_apply_previews', sa.Boolean(), nullable=True),
    sa.Column('wm_apply_thumbs', sa.Boolean(), nullable=True),
    sa.Column('wm_apply_downloads', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_settings')
    # ### end Alembic commands ###
