"""added gallery module

Revision ID: a2d606aa5c5c
Revises: f60dacc4ac56
Create Date: 2025-09-29 09:26:11.961676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d606aa5c5c'
down_revision: Union[str, Sequence[str], None] = 'f60dacc4ac56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.String(length=1024), nullable=True),
    sa.Column('watermark_path', sa.String(length=1024), nullable=True),
    sa.Column('watermark_opacity', sa.Integer(), nullable=True),
    sa.Column('watermark_scale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branding_id'), 'branding', ['id'], unique=False)
    op.create_index(op.f('ix_branding_owner_id'), 'branding', ['owner_id'], unique=False)
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleries_id'), 'galleries', ['id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('path_original', sa.String(length=1024), nullable=False),
    sa.Column('path_preview', sa.String(length=1024), nullable=True),
    sa.Column('path_thumb', sa.String(length=1024), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_gallery_id'), 'photos', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_gallery_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_galleries_id'), table_name='galleries')
    op.drop_table('galleries')
    op.drop_index(op.f('ix_branding_owner_id'), table_name='branding')
    op.drop_index(op.f('ix_branding_id'), table_name='branding')
    op.drop_table('branding')
    # ### end Alembic commands ###
