"""Added expiry and download

Revision ID: bb603aa43ae6
Revises: 95bbfb1c9458
Create Date: 2025-10-15 13:16:05.908278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb603aa43ae6'
down_revision: Union[str, Sequence[str], None] = '95bbfb1c9458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('galleries', sa.Column('download_count', sa.Integer(), nullable=True))
    op.add_column('galleries', sa.Column('download_limit', sa.Integer(), nullable=True, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galleries', 'download_limit')
    op.drop_column('galleries', 'download_count')
    op.drop_column('galleries', 'password_expires_at')
    # ### end Alembic commands ###
