"""update models

Revision ID: dba12409c55e
Revises: 95bbfb1c9458
Create Date: 2026-06-09 05:03:57.887063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba12409c55e'
down_revision: Union[str, Sequence[str], None] = '95bbfb1c9458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('galleries', sa.Column('expired_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # op.alter_column('photos', 'file_id',
    #            existing_type=sa.VARCHAR(length=36),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('photos', 'file_id',
    #            existing_type=sa.VARCHAR(length=36),
    #            nullable=True)
    op.drop_column('galleries', 'expired_at')
    op.drop_column('galleries', 'status')
    # ### end Alembic commands ###
