"""branding theme fields

Revision ID: dce5d9801572
Revises: 57e34f896742
Create Date: 2026-06-09 18:19:06.787308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce5d9801572'
down_revision: Union[str, Sequence[str], None] = '57e34f896742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branding', sa.Column('primary_color', sa.String(length=20), nullable=True))
    op.add_column('branding', sa.Column('secondary_color', sa.String(length=20), nullable=True))
    op.add_column('branding', sa.Column('accent_color', sa.String(length=20), nullable=True))
    op.add_column('branding', sa.Column('font_family', sa.String(length=100), nullable=True))
    op.add_column('branding', sa.Column('theme_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branding', 'theme_mode')
    op.drop_column('branding', 'font_family')
    op.drop_column('branding', 'accent_color')
    op.drop_column('branding', 'secondary_color')
    op.drop_column('branding', 'primary_color')
    # ### end Alembic commands ###
