"""alrs lead tables

Revision ID: ded4e75e51c2
Revises: 0b79fc7de341
Create Date: 2025-11-26 13:19:24.632722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ded4e75e51c2'
down_revision: Union[str, Sequence[str], None] = '0b79fc7de341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_ons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('PRINT', 'FRAME', 'EXTRA_PHOTOS', 'ALBUM_UPGRADE', 'VIDEO', 'OTHER', name='addoncategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_add_ons_id'), 'add_ons', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('MATERNITY', 'NEWBORN', 'COMBO', 'BABY_MILESTONE', 'FAMILY', name='packagecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('num_edited_photos', sa.Integer(), nullable=True),
    sa.Column('num_outfits', sa.Integer(), nullable=True),
    sa.Column('includes_album', sa.Boolean(), nullable=True),
    sa.Column('includes_prints', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=150), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=20), nullable=False),
    sa.Column('primary_contact_email', sa.String(length=150), nullable=True),
    sa.Column('lead_type', sa.Enum('MATERNITY', 'NEWBORN', 'MATERNITY_NEWBORN_COMBO', 'BABY_MILESTONE', 'FAMILY', 'OTHER', name='leadtype'), nullable=True),
    sa.Column('source', sa.Enum('INSTAGRAM_DM', 'WHATSAPP', 'WEBSITE_FORM', 'REFERRAL', 'FACEBOOK', 'WALK_IN', 'OTHER', name='leadsource'), nullable=True),
    sa.Column('source_details', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.Enum('NEW', 'QUALIFYING', 'QUALIFIED', 'QUOTED', 'TENTATIVE_BOOKING', 'BOOKED', 'SHOT', 'DELIVERED', 'CLOSED_LOST', name='leadstage'), nullable=True),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('preferred_month', sa.Date(), nullable=True),
    sa.Column('location_type_pref', sa.Enum('HOME', 'STUDIO', 'OUTDOOR', 'UNDECIDED', name='locationtype'), nullable=True),
    sa.Column('location_area_pref', sa.String(length=150), nullable=True),
    sa.Column('budget_band', sa.Enum('LT_10K', 'B10_20K', 'B20_40K', 'GT_40K', 'UNKNOWN', name='budgetband'), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('gestation_weeks', sa.Integer(), nullable=True),
    sa.Column('baby_dob', sa.Date(), nullable=True),
    sa.Column('baby_age_days', sa.Integer(), nullable=True),
    sa.Column('baby_age_weeks', sa.Integer(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_channel', sa.Enum('INSTAGRAM', 'WHATSAPP', 'WEBSITE_CHAT', name='channel'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('INSTAGRAM', 'WHATSAPP', 'WEBSITE_CHAT', name='channel'), nullable=False),
    sa.Column('external_thread_id', sa.String(length=255), nullable=False),
    sa.Column('current_state', sa.Enum('NEW_INQUIRY', 'QUALIFYING', 'PACKAGE_RECOMMENDATION', 'OBJECTION', 'BOOKING', 'POST_BOOKING_PRE_SHOOT', 'POST_SHOOT_DELIVERY', 'NURTURE_LONG_TERM', name='conversationstate'), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_thread_id', name='uq_conversations_channel_thread')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('MATERNITY', 'NEWBORN', 'COMBO', 'BABY_MILESTONE', 'FAMILY', name='sessiontype'), nullable=False),
    sa.Column('status', sa.Enum('TENTATIVE', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED', name='sessionstatus'), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_type', sa.Enum('HOME', 'STUDIO', 'OUTDOOR', 'UNDECIDED', name='locationtype'), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes_photographer', sa.Text(), nullable=True),
    sa.Column('notes_client_visible', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('QUOTE_REMINDER', 'BOOKING_NUDGE', 'NEWBORN_WINDOW', 'MILESTONE_6M', 'MILESTONE_1Y', 'REVIEW_REQUEST', 'UPSELL_ALBUM', 'OTHER', name='followuptype'), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'INSTAGRAM', 'EMAIL', name='followupchannel'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'CANCELLED', 'FAILED', name='followupstatus'), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Enum('AI', 'HUMAN', 'SYSTEM', name='followupcreatedby'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_id'), 'follow_ups', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='invoicestatus'), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('CLIENT', 'HUMAN_STAFF', 'AI_AGENT', 'SYSTEM', name='sendertype'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'FILE', 'TEMPLATE', name='contenttype'), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('intent_label', sa.String(length=50), nullable=True),
    sa.Column('handled_by_agent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('session_add_ons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('add_on_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['add_on_id'], ['add_ons.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_add_ons_id'), 'session_add_ons', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('type', sa.Enum('BOOKING_ADVANCE', 'BALANCE', 'ADD_ON', 'OTHER', name='paymenttype'), nullable=True),
    sa.Column('gateway', sa.Enum('RAZORPAY', 'STRIPE', 'CASH', 'UPI', 'BANK', 'OTHER', name='paymentgateway'), nullable=True),
    sa.Column('gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_session_add_ons_id'), table_name='session_add_ons')
    op.drop_table('session_add_ons')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_follow_ups_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_add_ons_id'), table_name='add_ons')
    op.drop_table('add_ons')
    # ### end Alembic commands ###
