"""added favorites

Revision ID: fd8eb52da5c5
Revises: 9f67b9357702
Create Date: 2025-10-01 07:14:55.169932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8eb52da5c5'
down_revision: Union[str, Sequence[str], None] = '9f67b9357702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('favorites_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galleries', 'favorites_limit')
    # ### end Alembic commands ###
